version: '3'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 4002:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: minutia
    volumes:
      - ./postgres:/var/lib/postgresql/data
